### ISSUE TITLE
Wrong ordering of houses / street

### ISSUE THREAD

**Issue by bveldkamp** [tracestrack/tracestrack-maps#21]
On the Oudegracht in Utrecht, houses seem to be rendered on top of the street, while in fact, these are cellars below street level. Carto has it right, this time.

![Screenshot_20240204-120016](https://github.com/tracestrack/tracestrack-maps/assets/7160755/bcccebab-4f8e-4cfc-a030-3aafff0083e0)

![Screenshot_20240204-120118](https://github.com/tracestrack/tracestrack-maps/assets/7160755/8a1d23f6-3979-4bc2-8b48-5760458d02c0)

https://www.openstreetmap.org/#map=19/52.09560/5.11659&layers=PN

**Comment by quinncnl** [comment]
Thanks for the report! Indeed the order is wrong. It's like this because of 3D building support in another map type: 

<img width="690" alt="Screenshot 2024-02-06 at 13 26 22" src="https://github.com/tracestrack/tracestrack-maps/assets/359745/ce369b07-d230-4614-9e8c-c7c9465dbf9f">

Since topo map doesn't support 3D buildings, we should render highways above buildings. Will fix soon.

**Comment by quinncnl** [comment]
Updated. Will be reloaded soon.
